### ISSUE TITLE
listOfItems component

### ISSUE THREAD

**Issue by RandInaim** [fack2/Hebron-must-see#21]
#10 #8  
list of items component is used as a shared component to show the list of places or guides 
each as a card component

### Acceptance criteria :100: 
- [ ] list of items 
- [ ] each item is a card 

     react route: `/places` or `/guides`
     api route: `api/places` or `/api/guides`

**Comment by FarahZaqout** [comment]
Routes in their current state are a little confusing to the reader. It might be better to write the routes in the page's technical issue.
