### ISSUE TITLE
Login component

### ISSUE THREAD

**Issue by Nadeen123** [fack2/Hebron-must-see#22]
#14 
The login component should contain two text input fields for the email and password and login button to log in to the website.

## Acceptance criteria:
  * [ ] Input for email
  * [ ] Input for password
  * [ ]  button
* react route: `/login`
* api route: `/api/login/`

**Comment by FarahZaqout** [comment]
How many inputs does the form have? Is it username and password? Is it by email instead of username?

I know the answer might seem obvious, but generally speaking, it's best to detail these things a bit more.

**Comment by Nadeen123** [comment]
@FarahZaqout
