### ISSUE TITLE
create filter component 

### ISSUE THREAD

**Issue by saharAdem** [fack2/Hebron-must-see#24]
#8 #10 
filter component is a shared component for places and guides.

## Acceptance criteria: 
* [] filter buttons  for places component
    * [ ] react route: `/places` or '/guides'
    * [ ] api route: `api/places` or '/api/guides'

* [ ] filters for places component
    * [ ] Cultural 
    * [ ] Religious 
    * [ ] Historical
    * [ ] Entertainment 

* [ ] filters for guides component
    * [ ] Arabic
    * [ ] English 
    * [ ] Spain
    * [ ] French
    * [ ] Italy
    * [ ] Chinese

**Comment by FarahZaqout** [comment]
How many filter buttons? What are the filter categories?
