### ISSUE TITLE
detailed page for guides 

### ISSUE THREAD

**Issue by RandInaim** [fack2/Hebron-must-see#25]
#6 
as  a user clicks on one of the guides from the {itemsList} of guides he should be redirected to another page to see details about the guide.

### Acceptance criteria:
- [ ] information about the guide including contact information 
- [ ] list of reviews for this guide
- [ ] button to review the guide 

     react route: `/guides/:id`
     api route: `/api/guides/:id`

**Comment by FarahZaqout** [comment]
What is the contact information? Is it by phone only, can we use mail? ..etc.
