### ISSUE TITLE
create menu 

### ISSUE THREAD

**Issue by SajaLahaleeh** [fack2/Hebron-must-see#28]
The menu exists on all of the website's pages exception start page, it contains a list of pages on a website: Home, Places, Guides, and Arabic List.

## Acceptance criteria:
* [ ] items list 
     * [ ] Home
          * react route: `/home`
          * api route: `/home`
     * [ ] Places
          * react route: `/places`
          * api route: `/places/`
     * [ ] Guides
         * react route:`/guides`
         * api route: `/guides`
     * [ ] Arabic List
          * react route: `/arabic-words`
          * api route: `/arabic-words/`

**Comment by FarahZaqout** [comment]
I would change the `arabicwords` to `arabic-words`.

**Comment by SajaLahaleeh** [comment]
I removed the `api` from the endpoint @FarahZaqout
