### ISSUE TITLE
Setup file structure /react app

### ISSUE THREAD

**Issue by SajaLahaleeh** [fack2/Hebron-must-see#29]

**Comment by FarahZaqout** [comment]
You should describe the file structure in the body of this issue. Otherwise no one really knows what to do with it.

**Comment by SajaLahaleeh** [comment]
- client
  - public
    - index.html
  - src
    - App.css
    - App.js
    - index.js
  - package.json
  - .gitignore
- server
  - controllers
    -Home
      - index.js
      - index.html
    -Guide
      - index.js
    -Places
      - index.js
    -ArabicList
      - index.js
  - database
  - app.js
  - server.js
  - router.js
- .env
- package.json
- .gitignore

**Comment by SajaLahaleeh** [comment]
This is a file structure @FarahZaqout 

- client
  - public
    - index.html
  - src
    - App.css
    - App.js
    - index.js
  - package.json
  - .gitignore
- server
  - controllers
    - Home
      - index.js
      - index.html
    - Guide
      - index.js
    - Places
      - index.js
    - ArabicList
      - index.js
  - database
  - app.js
  - server.js
  - router.js
- .env
- package.json
- .gitignore

**Comment by FarahZaqout** [comment]
There should be no html files inside the controllers.
